const roles = {
  /*"Public": {   //to be added on first time setup only
    content: {
      description: "Default role given to unauthenticated user.",
      type: "public"
    },
    controllers: [
      {
        name: "user",
        action: []
      },
      {
        name: "module",
        action: []
      },
      {
        name: "state",
        action: []
      },
      {
        name: "district",
        action: []
      },
      {
        name: "village",
        action: []
      },
      {
        name: "shg",
        action: []
      }
    ],
    grantAllPermissions: true
  },*/
  "FPO Admin": {
    content: {
      description: "FPO admin user",
      type: "",
    },
    controllers: [
      {
        name: "user",
        action: ["update"],
      },
      {
        name: "module",
        action: ["find", "count", "findone"],
      },
      {
        name: "state",
        action: ["find", "count", "findone", "create", "update", "delete"],
      },
      {
        name: "district",
        action: ["find", "count", "findone", "create", "update", "delete"],
      },
      {
        name: "village",
        action: ["find", "count", "findone", "create", "update", "delete"],
      },
      {
        name: "shg",
        action: ["find", "count", "findone", "create", "update", "delete"],
      },
    ],
    grantAllPermissions: false,
  },
  "Sesta Admin": {
    content: {
      description: "Sesta admin user",
      type: "",
    },
    controllers: [
      {
        name: "user",
        action: ["update"],
      },
      {
        name: "module",
        action: ["find", "count", "findone"],
      },
      {
        name: "state",
        action: ["find", "count", "findone", "create", "update", "delete"],
      },
      {
        name: "district",
        action: ["find", "count", "findone", "create", "update", "delete"],
      },
      {
        name: "village",
        action: ["find", "count", "findone", "create", "update", "delete"],
      },
      {
        name: "shg",
        action: ["find", "count", "findone", "create", "update", "delete"],
      },
    ],
    grantAllPermissions: false,
  },
  "CSP (Community Service Provider)": {
    content: {
      description: "Community service provider user",
      type: "",
    },
    controllers: [
      {
        name: "user",
        action: ["update"],
      },
      {
        name: "module",
        action: ["find", "count", "findone"],
      },
      {
        name: "state",
        action: [],
      },
      {
        name: "district",
        action: [],
      },
      {
        name: "village",
        action: [],
      },
      {
        name: "shg",
        action: [],
      },
    ],
    grantAllPermissions: false,
  },
  Superadmin: {
    content: {
      description: "Superadmin user",
      type: "",
    },
    controllers: [
      {
        name: "user",
        action: ["update"],
      },
      {
        name: "module",
        action: ["find", "count", "findone"],
      },
      {
        name: "state",
        action: ["find", "count", "findone", "create", "update", "delete"],
      },
      {
        name: "district",
        action: ["find", "count", "findone", "create", "update", "delete"],
      },
      {
        name: "village",
        action: ["find", "count", "findone", "create", "update", "delete"],
      },
      {
        name: "shg",
        action: ["find", "count", "findone", "create", "update", "delete"],
      },
    ],
    grantAllPermissions: false,
  },
};

const modules = {
  Dashboard: {
    is_active: true,
    icon_class: "dashboard",
    url: "/",
    slug: "home",
    displayNavigation: true,
    module: "", //slug
    roles: [
      "FPO Admin",
      "Sesta Admin",
      "CSP (Community Service Provider)",
      "Superadmin",
    ],
  },
  Villages: {
    is_active: true,
    icon_class: "people",
    url: "/villages",
    slug: "list_village",
    displayNavigation: true,
    module: "", //slug
    roles: ["FPO Admin", "Sesta Admin", "Superadmin"],
  },
  "Add Village": {
    is_active: true,
    icon_class: "",
    url: "/villages/add",
    slug: "add_village",
    displayNavigation: false,
    module: "", //slug
    roles: ["FPO Admin", "Sesta Admin", "Superadmin"],
  },
  "Edit Village": {
    is_active: true,
    icon_class: "",
    url: "/villages/edit/:id",
    slug: "edit_village",
    displayNavigation: false,
    module: "", //slug
    roles: ["FPO Admin", "Sesta Admin", "Superadmin"],
  },
  SHGs: {
    is_active: true,
    icon_class: "people",
    url: "/shgs",
    slug: "list_shg",
    displayNavigation: true,
    module: "", //slug
    roles: ["FPO Admin", "Sesta Admin", "Superadmin"],
  },
};

const districts = [
  // UT Andaman and Nicobar Island Districts
  // {
  //   name: "Nicobar",
  //   state_name: "Andaman and Nicobar Island",
  //   is_active: true,
  //   master_state: Number,
  // },
  // {
  //   name: "South Andaman",
  //   state_name: "Andaman and Nicobar Island",
  //   is_active: true,
  //   master_state: Number,
  // },
  // {
  //   name: "North and Middle Andaman",
  //   state_name: "Andaman and Nicobar Island",
  //   is_active: true,
  //   master_state: Number,
  // },
  //Andhra Pradesh Districts
  {
    name: "Anantapur",
    state_name: "Andhra Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Chittoor",
    state_name: "Andhra Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "East Godavari",
    state_name: "Andhra Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Guntur",
    state_name: "Andhra Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Krishna",
    state_name: "Andhra Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kurnool",
    state_name: "Andhra Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Prakasam",
    state_name: "Andhra Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Srikakulam",
    state_name: "Andhra Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sri Potti Sriramulu Nellore",
    state_name: "Andhra Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Visakhapatnam",
    state_name: "Andhra Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Vizianagaram",
    state_name: "Andhra Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "West Godavari",
    state_name: "Andhra Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "YSR District, Kadapa (Cuddapah)",
    state_name: "Andhra Pradesh",
    is_active: true,
    master_state: Number,
  },
  //Arunachal Pradesh districts
  {
    name: "Anjaw",
    state_name: "Arunachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Changlang",
    state_name: "Arunachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Dibang Valley",
    state_name: "Arunachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "East Kameng",
    state_name: "Arunachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "East Siang",
    state_name: "Arunachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kamle",
    state_name: "Arunachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kra Daadi",
    state_name: "Arunachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kurung Kumey",
    state_name: "Arunachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Lepa Rada",
    state_name: "Arunachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Lohit",
    state_name: "Arunachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Longding",
    state_name: "Arunachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Lower Dibang Valley",
    state_name: "Arunachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Lower Siang",
    state_name: "Arunachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Lower Subansiri",
    state_name: "Arunachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Namsai",
    state_name: "Arunachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Pakke Kessang",
    state_name: "Arunachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Papum Pare",
    state_name: "Arunachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Shi Yomi",
    state_name: "Arunachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Siang",
    state_name: "Arunachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Tawang",
    state_name: "Arunachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Tirap",
    state_name: "Arunachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Upper Siang",
    state_name: "Arunachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Upper Subansiri",
    state_name: "Arunachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "West Kameng",
    state_name: "Arunachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "West Siang",
    state_name: "Arunachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  //Assam Districts
  {
    name: "Baksa",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Barpeta",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Biswanath",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bongaigaon",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Cachar",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Charaideo",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Chirang",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Darrang",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Dhemaji",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Dhubri",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Dibrugarh",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Dima Hasao (North Cachar Hills)",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Goalpara",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Golaghat",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Hailakandi",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Hojai",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jorhat",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jorhat",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kamrup Metropolitan",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Karbi Anglong",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Karimganj",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kokrajhar",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Lakhimpur",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Majuli",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Morigaon",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Nagaon",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Nalbari",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sivasagar",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sonitpur",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "South Salamara-Mankachar",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Tinsukia",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Udalguri",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  {
    name: "West Karbi Anglong",
    state_name: "Assam",
    is_active: true,
    master_state: Number,
  },
  //Bihar Districts
  {
    name: "Araria",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Arwal",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Aurangabad",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Banka",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Begusarai",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bhagalpur",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bhagalpur",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Buxar",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Darbhanga",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "East Champaran (Motihari)",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Gaya",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Gopalganj",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jamui",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jehanabad",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kaimur (Bhabua)",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Katihar",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Khagaria",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kishanganj",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Lakhisarai",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Madhepura",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Madhubani",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Munger (Monghyr)",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Muzaffarpur",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Nalanda",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Nawada",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Patna",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Purnia (Purnea)",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Rohtas",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Saharsa",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Samastipur",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Saran",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sheikhpura",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sheohar",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sitamarhi",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Siwan",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Supaul",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Vaishali",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  {
    name: "West Champaran",
    state_name: "Bihar",
    is_active: true,
    master_state: Number,
  },
  //UT Chandigarh Districts
  // {
  //   name: "Chandigarh",
  //   state_name: "Chandigarh",
  //   is_active: true,
  //   master_state: Number,
  // },

  //Chhattisgarh Districts
  {
    name: "Balod",
    state_name: "Chhattisgarh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Baloda Bazar",
    state_name: "Chhattisgarh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Balrampur",
    state_name: "Chhattisgarh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bastar",
    state_name: "Chhattisgarh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bemetara",
    state_name: "Chhattisgarh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bijapur",
    state_name: "Chhattisgarh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bilaspur",
    state_name: "Chhattisgarh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Dantewada (South Bastar)",
    state_name: "Chhattisgarh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Dhamtari",
    state_name: "Chhattisgarh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Durg",
    state_name: "Chhattisgarh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Gariyaband",
    state_name: "Chhattisgarh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Janjgir-Champa",
    state_name: "Chhattisgarh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jashpur",
    state_name: "Chhattisgarh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kabirdham (Kawardha)",
    state_name: "Chhattisgarh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kanker (North Bastar)",
    state_name: "Chhattisgarh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kondagaon",
    state_name: "Chhattisgarh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Korba",
    state_name: "Chhattisgarh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Korea (Koriya)",
    state_name: "Chhattisgarh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Mahasamund",
    state_name: "Chhattisgarh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Mungeli",
    state_name: "Chhattisgarh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Narayanpur",
    state_name: "Chhattisgarh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Raigarh",
    state_name: "Chhattisgarh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Raipur",
    state_name: "Chhattisgarh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Rajnandgaon",
    state_name: "Chhattisgarh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sukma",
    state_name: "Chhattisgarh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Surajpur",
    state_name: "Chhattisgarh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Surguja",
    state_name: "Chhattisgarh",
    is_active: true,
    master_state: Number,
  },

  //UT Dadra and Nagar Haveli dist
  // {
  //   name: "Dadra & Nagar Haveli",
  //   state_name: "Dadra & Nagar Haveli",
  //   is_active: true,
  //   master_state: Number,
  // },

  //UT Daman and Diu disticts
  // {
  //   name: "Daman",
  //   state_name: "Daman and Diu",
  //   is_active: true,
  //   master_state: Number,
  // },
  // {
  //   name: "Diu",
  //   state_name: "Daman and Diu",
  //   is_active: true,
  //   master_state: Number,
  // },
  //Delhi districts
  {
    name: "Central Delhi",
    state_name: "Delhi",
    is_active: true,
    master_state: Number,
  },
  {
    name: "East Delhi",
    state_name: "Delhi",
    is_active: true,
    master_state: Number,
  },
  {
    name: "New Delhi",
    state_name: "Delhi",
    is_active: true,
    master_state: Number,
  },
  {
    name: "North Delhi",
    state_name: "Delhi",
    is_active: true,
    master_state: Number,
  },
  {
    name: "North East Delhi",
    state_name: "Delhi",
    is_active: true,
    master_state: Number,
  },
  {
    name: "North West Delhi",
    state_name: "Delhi",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Shahdara",
    state_name: "Delhi",
    is_active: true,
    master_state: Number,
  },
  {
    name: "South Delhi",
    state_name: "Delhi",
    is_active: true,
    master_state: Number,
  },
  {
    name: "South East Delhi",
    state_name: "Delhi",
    is_active: true,
    master_state: Number,
  },
  {
    name: "South West Delhi",
    state_name: "Delhi",
    is_active: true,
    master_state: Number,
  },
  {
    name: "West Delhi",
    state_name: "Delhi",
    is_active: true,
    master_state: Number,
  },
  //Goa districts 2
  {
    name: "North Goa",
    state_name: "Goa",
    is_active: true,
    master_state: Number,
  },
  {
    name: "South Goa",
    state_name: "Goa",
    is_active: true,
    master_state: Number,
  },
  //Gujarat districts 33
  {
    name: "Ahmedabad",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Amreli",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Anand",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Aravalli",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Banaskantha (Palanpur)",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bharuch",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bhavnagar",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Botad",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Chhota Udepur",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Dahod",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Dangs (Ahwa)",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Devbhoomi Dwarka",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Gandhinagar",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Gir Somnath",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jamnagar",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Junagadh",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kachchh",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kheda (Nadiad)",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Mahisagar",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Mehsana",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Morbi",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Narmada (Rajpipla)",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Navsari",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Panchmahal (Godhra)",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Patan",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Porbandar",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Rajkot",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sabarkantha (Himmatnagar)",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Surat",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Surendranagar",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Tapi (Vyara)",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Vadodara",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Valsad",
    state_name: "Gujarat",
    is_active: true,
    master_state: Number,
  },
  //Haryana Districts 22
  {
    name: "Ambala",
    state_name: "Haryana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bhiwani",
    state_name: "Haryana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Charkhi Dadri",
    state_name: "Haryana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Faridabad",
    state_name: "Haryana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Fatehabad",
    state_name: "Haryana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Gurugram (Gurgaon)",
    state_name: "Haryana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Hisar",
    state_name: "Haryana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jhajjar",
    state_name: "Haryana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jind",
    state_name: "Haryana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kaithal",
    state_name: "Haryana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Karnal",
    state_name: "Haryana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kurukshetra",
    state_name: "Haryana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Mahendragarh",
    state_name: "Haryana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Nuh",
    state_name: "Haryana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Palwal",
    state_name: "Haryana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Panchkula",
    state_name: "Haryana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Panipat",
    state_name: "Haryana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Rewari",
    state_name: "Haryana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Rohtak",
    state_name: "Haryana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sirsa",
    state_name: "Haryana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sonipat",
    state_name: "Haryana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Yamunanagar",
    state_name: "Haryana",
    is_active: true,
    master_state: Number,
  },
  //Himachal Pradesh Districts 12
  {
    name: "Bilaspur",
    state_name: "Himachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Chamba",
    state_name: "Himachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Hamirpur",
    state_name: "Himachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kangra",
    state_name: "Himachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kinnaur",
    state_name: "Himachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kullu",
    state_name: "Himachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Lahaul & Spiti",
    state_name: "Himachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Mandi",
    state_name: "Himachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Shimla",
    state_name: "Himachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sirmaur (Sirmour)",
    state_name: "Himachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Solan",
    state_name: "Himachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Una",
    state_name: "Himachal Pradesh",
    is_active: true,
    master_state: Number,
  },
  //Jammu and Kashmir Districts 22
  {
    name: "Anantnag",
    state_name: "Jammu and Kashmir",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bandipore",
    state_name: "Jammu and Kashmir",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Baramulla",
    state_name: "Jammu and Kashmir",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Budgam",
    state_name: "Jammu and Kashmir",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Doda",
    state_name: "Jammu and Kashmir",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Ganderbal",
    state_name: "Jammu and Kashmir",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jammu",
    state_name: "Jammu and Kashmir",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kargil",
    state_name: "Jammu and Kashmir",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kathua",
    state_name: "Jammu and Kashmir",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kishtwar",
    state_name: "Jammu and Kashmir",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kulgam",
    state_name: "Jammu and Kashmir",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kupwara",
    state_name: "Jammu and Kashmir",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Leh",
    state_name: "Jammu and Kashmir",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Poonch",
    state_name: "Jammu and Kashmir",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Pulwama",
    state_name: "Jammu and Kashmir",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Rajouri",
    state_name: "Jammu and Kashmir",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Ramban",
    state_name: "Jammu and Kashmir",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Reasi",
    state_name: "Jammu and Kashmir",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Samba",
    state_name: "Jammu and Kashmir",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Shopian",
    state_name: "Jammu and Kashmir",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Srinagar",
    state_name: "Jammu and Kashmir",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Udhampur",
    state_name: "Jammu and Kashmir",
    is_active: true,
    master_state: Number,
  },
  //Jharkhand districts 24
  {
    name: "Bokaro",
    state_name: "Jharkhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Chatra",
    state_name: "Jharkhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Deoghar",
    state_name: "Jharkhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Dhanbad",
    state_name: "Jharkhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Dumka",
    state_name: "Jharkhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "East Singhbhum",
    state_name: "Jharkhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Garhwa",
    state_name: "Jharkhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Giridih",
    state_name: "Jharkhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Godda",
    state_name: "Jharkhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Gumla",
    state_name: "Jharkhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Hazaribag",
    state_name: "Jharkhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jamtara",
    state_name: "Jharkhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Khunti",
    state_name: "Jharkhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Koderma",
    state_name: "Jharkhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Latehar",
    state_name: "Jharkhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Lohardaga",
    state_name: "Jharkhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Pakur",
    state_name: "Jharkhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Palamu",
    state_name: "Jharkhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Ramgarh",
    state_name: "Jharkhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Ranchi",
    state_name: "Jharkhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sahibganj",
    state_name: "Jharkhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Seraikela-Kharsawan",
    state_name: "Jharkhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Simdega",
    state_name: "Jharkhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "West Singhbhum",
    state_name: "Jharkhand",
    is_active: true,
    master_state: Number,
  },
  //Karnataka Dist 30
  {
    name: "Bagalkot",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Ballari (Bellary)",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Belagavi (Belgaum)",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bengaluru (Bangalore) Rural",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bengaluru (Bangalore) Rural",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bidar",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Chamarajanagar",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Chikballapur",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Chikkamagaluru (Chikmagalur)",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Chitradurga",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Dakshina Kannada",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Davangere",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Dharwad",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Gadag",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Gadag",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Hassan",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Haveri",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kalaburagi (Gulbarga)",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kodagu",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kolar",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Koppal",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Mandya",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Mysuru (Mysore)",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Raichur",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Ramanagara",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Shivamogga (Shimoga)",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Tumakuru (Tumkur)",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Udupi",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: " Uttara Kannada (Karwar)",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Vijayapura (Bijapur)",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Yadgir",
    state_name: "Karnataka",
    is_active: true,
    master_state: Number,
  },
  //Kerela dist 14
  {
    name: "Alappuzha",
    state_name: "Kerela",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Ernakulam",
    state_name: "Kerela",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Idukki",
    state_name: "Kerela",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kannur",
    state_name: "Kerela",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kasaragod",
    state_name: "Kerela",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kollam",
    state_name: "Kerela",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kottayam",
    state_name: "Kerela",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kozhikode",
    state_name: "Kerela",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Malappuram",
    state_name: "Kerela",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Palakkad",
    state_name: "Kerela",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Pathanamthitta",
    state_name: "Kerela",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Thiruvananthapuram",
    state_name: "Kerela",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Thrissur",
    state_name: "Kerela",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Wayanad",
    state_name: "Kerela",
    is_active: true,
    master_state: Number,
  },
  //UT Lakshadweep 1
  // {
  //   name: "Lakshadweep",
  //   state_name: "Lakshadweep",
  //   is_active: true,
  //   master_state: Number,
  // },
  //Madhya Pradesh dist 52
  {
    name: "Agar Malwa",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Alirajpur",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Anuppur",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Ashoknagar",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Balaghat",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Barwani",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Betul",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bhind",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bhopal",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Burhanpur",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Chhatarpur",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Chhindwara",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Damoh",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Datia",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Dewas",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Dhar",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Dindori",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Guna",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Gwalior",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Harda",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Hoshangabad",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Indore",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jabalpur",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jhabua",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Katni",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Khandwa",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Khargone",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Mandla",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Mandsaur",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Morena",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Narsinghpur",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Neemuch",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Niwari",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Panna",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Raisen",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Rajgarh",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Ratlam",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Rewa",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sagar",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Satna",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sehore",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Seoni",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Shahdol",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Shajapur",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sheopur",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Shivpuri",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sidhi",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Singrauli",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Tikamgarh",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Ujjain",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Umaria",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Vidisha",
    state_name: "Madhya Pradesh",
    is_active: true,
    master_state: Number,
  },
  // Maharashtra dist 36
  {
    name: "Ahmednagar",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Akola",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Amravati",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Aurangabad",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Beed",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bhandara",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Buldhana",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Chandrapur",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Dhule",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Gadchiroli",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Gondia",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Hingoli",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jalgaon",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jalna",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kolhapur",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Latur",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Mumbai City",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Mumbai Suburban",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Nagpur",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Nanded",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Nandurbar",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Nashik",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Osmanabad",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Palghar",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Parbhani",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Pune",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Raigad",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Ratnagiri",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sangli",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Satara",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sindhudurg",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Solapur",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Thane",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Wardha",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Washim",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Yavatmal",
    state_name: "Maharashtra",
    is_active: true,
    master_state: Number,
  },
  //Manipur dist 16
  {
    name: "Bishnupur",
    state_name: "Manipur",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Chandel",
    state_name: "Manipur",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Churachandpur",
    state_name: "Manipur",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Imphal East",
    state_name: "Manipur",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Imphal West",
    state_name: "Manipur",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jiribam",
    state_name: "Manipur",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kakching",
    state_name: "Manipur",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kamjong",
    state_name: "Manipur",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kangpokpi",
    state_name: "Manipur",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Noney",
    state_name: "Manipur",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Pherzawl",
    state_name: "Manipur",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Senapati",
    state_name: "Manipur",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Tamenglong",
    state_name: "Manipur",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Tengnoupal",
    state_name: "Manipur",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Thoubal",
    state_name: "Manipur",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Ukhrul",
    state_name: "Manipur",
    is_active: true,
    master_state: Number,
  },
  //Meghalaya dist 11
  {
    name: "East Garo Hills",
    state_name: "Meghalaya",
    is_active: true,
    master_state: Number,
  },
  {
    name: "East Jaintia Hills",
    state_name: "Meghalaya",
    is_active: true,
    master_state: Number,
  },
  {
    name: "East Khasi Hills",
    state_name: "Meghalaya",
    is_active: true,
    master_state: Number,
  },
  {
    name: "North Garo Hills",
    state_name: "Meghalaya",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Ri Bhoi",
    state_name: "Meghalaya",
    is_active: true,
    master_state: Number,
  },
  {
    name: "South Garo Hills",
    state_name: "Meghalaya",
    is_active: true,
    master_state: Number,
  },
  {
    name: "South West Garo Hills",
    state_name: "Meghalaya",
    is_active: true,
    master_state: Number,
  },
  {
    name: "South West Khasi Hills",
    state_name: "Meghalaya",
    is_active: true,
    master_state: Number,
  },
  {
    name: "West Garo Hills",
    state_name: "Meghalaya",
    is_active: true,
    master_state: Number,
  },
  {
    name: "West Jaintia Hills",
    state_name: "Meghalaya",
    is_active: true,
    master_state: Number,
  },
  {
    name: "West Khasi Hills",
    state_name: "Meghalaya",
    is_active: true,
    master_state: Number,
  },
  //Mizoram dist 8
  {
    name: "Aizawl",
    state_name: "Mizoram",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Champhai",
    state_name: "Mizoram",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kolasib",
    state_name: "Mizoram",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Lawngtlai",
    state_name: "Mizoram",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Lunglei",
    state_name: "Mizoram",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Mamit",
    state_name: "Mizoram",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Saiha",
    state_name: "Mizoram",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Serchhip",
    state_name: "Mizoram",
    is_active: true,
    master_state: Number,
  },
  //Nagaland dist 11
  {
    name: "Dimapur",
    state_name: "Nagaland",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kiphire",
    state_name: "Nagaland",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kohima",
    state_name: "Nagaland",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Longleng",
    state_name: "Nagaland",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Mokokchung",
    state_name: "Nagaland",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Mon",
    state_name: "Nagaland",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Peren",
    state_name: "Nagaland",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Phek",
    state_name: "Nagaland",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Tuensang",
    state_name: "Nagaland",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Wokha",
    state_name: "Nagaland",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Zunheboto",
    state_name: "Nagaland",
    is_active: true,
    master_state: Number,
  },
  //Odisha dist 30
  {
    name: "Angul",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Balangir",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Balasore",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bargarh",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bhadrak",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Boudh",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Cuttack",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Deogarh",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Dhenkanal",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Gajapati",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Ganjam",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jagatsinghapur",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jajpur",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jharsuguda",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kalahandi",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kandhamal",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kendrapara",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kendujhar (Keonjhar)",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Khordha",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Koraput",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Malkangiri",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Mayurbhanj",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Nabarangpur",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Nayagarh",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Nuapada",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Puri",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Rayagada",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sambalpur",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sonepur",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sundargarh",
    state_name: "Odisha",
    is_active: true,
    master_state: Number,
  },
  //UT Puducherry dist 4
  {
    name: "Karaikal",
    state_name: "Puducherry",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Mahe",
    state_name: "Puducherry",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Puducherry",
    state_name: "Puducherry",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Yanam",
    state_name: "Puducherry",
    is_active: true,
    master_state: Number,
  },
  //Punjab dist 22
  {
    name: "Amritsar",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Barnala",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bathinda",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Faridkot",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Fatehgarh Sahib",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Fazilka",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Ferozepur",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Gurdaspur",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Hoshiarpur",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jalandhar",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kapurthala",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Ludhiana",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Mansa",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Moga",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Muktsar",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Nawanshahr (Shahid Bhagat Singh Nagar)",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Pathankot",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Patiala",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Rupnagar",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sahibzada Ajit Singh Nagar (Mohali)",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sangrur",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Tarn Taran",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  //Rajasthan dist 33
  {
    name: "Ajmer",
    state_name: "Rajasthan",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Alwar",
    state_name: "Rajasthan",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Banswara",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Baran",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Barmer",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bharatpur",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bhilwara",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bikaner",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bundi",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Chittorgarh",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Churu",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Dausa",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Dholpur",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Dungarpur",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Hanumangarh",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jaipur",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jaisalmer",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jalore",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jhalawar",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jhunjhunu",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jodhpur",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Karauli",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kota",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Nagaur",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Pali",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Pratapgarh",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Rajsamand",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sawai Madhopur",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sikar",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sirohi",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sri Ganganagar",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Tonk",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Udaipur",
    state_name: "Punjab",
    is_active: true,
    master_state: Number,
  },
  //Sikkim dist 4
  {
    name: "East Sikkim",
    state_name: "Sikkim",
    is_active: true,
    master_state: Number,
  },
  {
    name: "West Sikkim",
    state_name: "Sikkim",
    is_active: true,
    master_state: Number,
  },
  {
    name: "North Sikkim",
    state_name: "Sikkim",
    is_active: true,
    master_state: Number,
  },
  {
    name: "South Sikkim",
    state_name: "Sikkim",
    is_active: true,
    master_state: Number,
  },
  //Tamil Nadu dist 37
  {
    name: "Ariyalur",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Chengalpattu",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Chennai",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Coimbatore",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Cuddalore",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Dharmapuri",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: " Dindigul",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Erode",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kallakurichi",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kanchipuram",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kanyakumari",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Karur",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Karur",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Madurai",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Nagapattinam",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Namakkal",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Nilgiris",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Perambalur",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Pudukkottai",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Ramanathapuram",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Ranipet",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Salem",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sivaganga",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Tenkasi",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Thanjavur",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Theni",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Thoothukudi (Tuticorin)",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Tiruchirappalli",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Tirunelveli",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Tirupathur",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Tiruppur",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Tiruvallur",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Tiruvannamalai",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Tiruvarur",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Vellore",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Viluppuram",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Virudhunagar",
    state_name: "Tamil Nadu",
    is_active: true,
    master_state: Number,
  },
  //Telangana dist 37
  {
    name: "Adilabad",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bhadradri Kothagudem",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Hyderabad",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jagtial",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jangaon",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jayashankar Bhoopalpally",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jogulamba Gadwal",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kamareddy",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Karimnagar",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Khammam",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Komaram Bheem Asifabad",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Mahabubabad",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Mahabubnagar",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Mancherial",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Medak",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Medchal",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Nagarkurnool",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Nalgonda",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Nirmal",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Nizamabad",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Peddapalli",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Rajanna Sircilla",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Rangareddy",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sangareddy",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Siddipet",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Suryapet",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Vikarabad",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Wanaparthy",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Warangal (Rural)",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Warangal (Urban)",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Yadadri Bhuvanagiri",
    state_name: "Telangana",
    is_active: true,
    master_state: Number,
  },
  //Tripura dist 8
  {
    name: "Dhalai",
    state_name: "Tripura",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Gomati",
    state_name: "Tripura",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Khowai",
    state_name: "Tripura",
    is_active: true,
    master_state: Number,
  },
  {
    name: "North Tripura",
    state_name: "Tripura",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sepahijala",
    state_name: "Tripura",
    is_active: true,
    master_state: Number,
  },
  {
    name: "South Tripura",
    state_name: "Tripura",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Unakoti",
    state_name: "Tripura",
    is_active: true,
    master_state: Number,
  },
  {
    name: "West Tripura",
    state_name: "Tripura",
    is_active: true,
    master_state: Number,
  },
  //Uttarakhand dist 13
  {
    name: "Almora",
    state_name: "Uttarakhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bageshwar",
    state_name: "Uttarakhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Chamoli",
    state_name: "Uttarakhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Champawat",
    state_name: "Uttarakhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Dehradun",
    state_name: "Uttarakhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Dehradun",
    state_name: "Uttarakhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: " Nainital",
    state_name: "Uttarakhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Haridwar",
    state_name: "Uttarakhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Pauri Garhwal",
    state_name: "Uttarakhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Pithoragarh",
    state_name: "Uttarakhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Rudraprayag",
    state_name: "Uttarakhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Tehri Garhwal",
    state_name: "Uttarakhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Udham Singh Nagar",
    state_name: "Uttarakhand",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Uttarkashi",
    state_name: "Uttarakhand",
    is_active: true,
    master_state: Number,
  },
  //Uttar Pradesh dist 75
  {
    name: "Agra",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Aligarh",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Allahabad",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Ambedkar Nagar",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Amethi (Chatrapati Sahuji Mahraj Nagar)",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Amroha (J.P. Nagar)",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Auraiya",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Azamgarh",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Baghpat",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bahraich",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Ballia",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Balrampur",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Banda",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Barabanki",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bareilly",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Basti",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bhadohi",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bijnor",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Budaun",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bulandshahr",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Chandauli",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Chitrakoot",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Deoria",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Etah",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Etawah",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Faizabad",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Farrukhabad",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Fatehpur",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Firozabad",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Gautam Buddha Nagar",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Ghaziabad",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Ghazipur",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Gonda",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Gorakhpur",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Hamirpur",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Hapur (Panchsheel Nagar)",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Hardoi",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Hathras",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jalaun",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jaunpur",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jhansi",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kannauj",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kanpur Dehat",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kanpur Nagar",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kanshiram Nagar (Kasganj)",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kaushambi",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kushinagar (Padrauna)",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Lakhimpur - Kheri",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Lalitpur",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Lucknow",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Maharajganj",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Mahoba",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Mainpuri",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Mathura",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Mau",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Meerut",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Mirzapur",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Moradabad",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Muzaffarnagar",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Pilibhit",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Pratapgarh",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "RaeBareli",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Rampur",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Saharanpur",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sambhal (Bhim Nagar)",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sant Kabir Nagar",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Shahjahanpur",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Shamali (Prabuddh Nagar)",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Shravasti",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Siddharth Nagar",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sitapur",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sonbhadra",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Sultanpur",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Unnao",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Varanasi",
    state_name: "Uttar Pradesh",
    is_active: true,
    master_state: Number,
  },
  //West Bengal 23
  {
    name: "Alipurduar",
    state_name: "West Bengal",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Bankura",
    state_name: "West Bengal",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Birbhum",
    state_name: "West Bengal",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Cooch Behar",
    state_name: "West Bengal",
    is_active: true,
    master_state: Number,
  },
  {
    name: " Dakshin Dinajpur (South Dinajpur)",
    state_name: "West Bengal",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Darjeeling",
    state_name: "West Bengal",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Hooghly",
    state_name: "West Bengal",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Howrah",
    state_name: "West Bengal",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jalpaiguri",
    state_name: "West Bengal",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Jhargram",
    state_name: "West Bengal",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kalimpong",
    state_name: "West Bengal",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Kolkata",
    state_name: "West Bengal",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Malda",
    state_name: "West Bengal",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Murshidabad",
    state_name: "West Bengal",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Nadia",
    state_name: "West Bengal",
    is_active: true,
    master_state: Number,
  },
  {
    name: "North 24 Parganas",
    state_name: "West Bengal",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Paschim Medinipur (West Medinipur)",
    state_name: "West Bengal",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Paschim (West) Burdwan (Bardhaman)",
    state_name: "West Bengal",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Purba Burdwan (Bardhaman)",
    state_name: "West Bengal",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Purba Medinipur (East Medinipur)",
    state_name: "West Bengal",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Purulia",
    state_name: "West Bengal",
    is_active: true,
    master_state: Number,
  },
  {
    name: "South 24 Parganas",
    state_name: "West Bengal",
    is_active: true,
    master_state: Number,
  },
  {
    name: "Uttar Dinajpur (North Dinajpur)",
    state_name: "West Bengal",
    is_active: true,
    master_state: Number,
  },
];

const states = [
  // {
  //   name: "Andaman and Nicobar Island",
  //   is_active: true,
  // },
  {
    name: "Andhra Pradesh",
    is_active: true,
  },
  {
    name: "Arunachal Pradesh",
    is_active: true,
  },
  {
    name: "Assam",
    is_active: true,
  },
  {
    name: "Bihar",
    is_active: true,
  },
  // {
  //   name: "Chandigarh",
  //   is_active: true,
  // },
  {
    name: "Chhattisgarh",
    is_active: true,
  },
  // {
  //   name: "Dadra and Nagar Haveli",
  //   is_active: true,
  // },
  // {
  //   name: "Daman and Diu",
  //   is_active: true,
  // },
  {
    name: "Delhi",
    is_active: true,
  },
  {
    name: "Goa",
    is_active: true,
  },
  {
    name: "Gujarat",
    is_active: true,
  },
  {
    name: "Haryana",
    is_active: true,
  },
  {
    name: "Himachal Pradesh",
    is_active: true,
  },
  {
    name: "Jammu and Kashmir",
    is_active: true,
  },
  {
    name: "Jharkhand",
    is_active: true,
  },
  {
    name: "Karnataka",
    is_active: true,
  },
  {
    name: "Kerala",
    is_active: true,
  },
  // {
  //   name: "Lakshadweep",
  //   is_active: true,
  // },
  {
    name: "Madhya Pradesh",
    is_active: true,
  },
  {
    name: "Maharashtra ",
    is_active: true,
  },
  {
    name: "Manipur",
    is_active: true,
  },
  {
    name: "Meghalaya",
    is_active: true,
  },
  {
    name: "Mizoram",
    is_active: true,
  },
  {
    name: "Nagaland",
    is_active: true,
  },
  {
    name: "Odisha",
    is_active: true,
  },
  // {
  //   name: "Puducherry",
  //   is_active: true,
  // },
  {
    name: "Punjab",
    is_active: true,
  },
  {
    name: "Rajasthan",
    is_active: true,
  },
  {
    name: "Sikkim",
    is_active: true,
  },
  {
    name: "TamilNadu",
    is_active: true,
  },
  {
    name: "Telangana",
    is_active: true,
  },
  {
    name: "Tripura",
    is_active: true,
  },
  {
    name: "Uttarakhand",
    is_active: true,
  },
  {
    name: "Uttar Pradesh",
    is_active: true,
  },
  {
    name: "West Bengal",
    is_active: true,
  },
];
module.exports = Object.freeze({
  roles,
  modules,
  states,
  districts,
});
